### PR TITLE
[client] Event system rework

### PR DESCRIPTION
**Pull request by cloudhead**
*See commits*

### CODE REVIEW

**Comment by cryptoquick** [comment]
In this context, what is the difference between a promise and a future? Am I correct in understanding that you've implemented your own execution engine, Reactor, instead of adopting one of the more commonly used ones?

**Comment by cloudhead** [comment]
> In this context, what is the difference between a promise and a future? Am I correct in understanding that you've implemented your own execution engine, Reactor, instead of adopting one of the more commonly used ones?

I dropped the idea in the end, as it's not really necessary, nor is it a good idea. I think this sort of API will be best served by an async client in the future.

**Comment by cryptoquick** [comment]
Makes sense! I realize Rust's async situation is tricky. I don't have a strong opinion either way, from a high level they're all pretty similar.

**Comment by cloudhead** [comment]
> Makes sense! I realize Rust's async situation is tricky. I don't have a strong opinion either way, from a high level they're all pretty similar.

Yeah, I originally started this project with an async runtime and it was a huge pain. I then decided to build around threads and `poll`, which ended up being a lot easier!

**Pull request merged**
