### PR TITLE
Fix the signet genesis block

### PR DESCRIPTION
**Pull request by danielabrozzoni**
It was previously encoded in reverse order.

To test, try starting a nakamoto node (on master) in signet, shutting it down, and restarting it: it will fail with the `GenesisMismatch` error. Instead, if you try to do the same in this branch, it will work.

### CODE REVIEW

**Review by cloudhead — APPROVED** [review]
You're correct, the zero bits are at the end!

**Review by vincenzopalazzo — APPROVED** [review]
LGTM, but I have a question, why we do not move the array of bytes into a string? We could get the same result with `"...".as_bytes()` but at least we have a human-readable string to manage

**Comment by cloudhead** [comment]
> LGTM, but I have a question, why we do not move the array of bytes into a string? We could get the same result with `"...".as_bytes()` but at least we have a human-readable string to manage

The reason is that if we use a string, we still need to convert it to a hash, and that is fallible. This way all conversions are guaranteed to succeed.

**Comment by RandyMcMillan** [comment]
recomend bumpimg a release with this fix in it

**Pull request merged**
